# Generated by Django 4.2.5 on 2024-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_message", "0002_alter_message_chat_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="vizualized",
            field=models.BooleanField(default=False),
        ),
    ]
