# Generated by Django 4.2.5 on 2024-10-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_role_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[("client", "Client"), ("provider", "Provider")],
                default="client",
                max_length=10,
            ),
        ),
    ]
