# Generated by Django 4.2.5 on 2024-10-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_profile_profile_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_type",
        ),
        migrations.AddField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[("client", "Client"), ("provider", "Provider")],
                default="client",
                max_length=10,
            ),
        ),
    ]
