# Generated by Django 4.2.5 on 2024-09-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("appointment", "0002_review_service_alter_review_id_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="document",
            field=models.ManyToManyField(
                related_name="appointments", to="documents.document"
            ),
        ),
    ]
