# Generated by Django 4.2.5 on 2024-10-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documenttemplate_servicedocumentrequirement"),
        ("appointment", "0003_appointment_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="document",
        ),
        migrations.AddField(
            model_name="appointment",
            name="documents",
            field=models.ManyToManyField(
                related_name="appointments", to="documents.document"
            ),
        ),
    ]
