# Generated by Django 4.2.5 on 2024-10-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_remove_user_is_staff"),
        ("appointment", "0004_remove_appointment_document_appointment_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.user",
            ),
            preserve_default=False,
        ),
    ]
