# Generated by Django 4.2.5 on 2024-10-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_servicedocumentrequirement_document_template"),
        ("appointment", "0008_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="appointments",
                to="documents.document",
            ),
        ),
    ]
