# Generated by Django 4.2.5 on 2024-11-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_appointment_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
    ]
