# Generated by Django 4.2.5 on 2024-12-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_remove_user_is_staff"),
        ("appointment", "0013_alter_review_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_appointments",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_appointments",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="appointment.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="authentication.user"
            ),
        ),
    ]
