# Generated by Django 4.2.5 on 2024-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_alter_documenttemplate_document_and_more"),
        (
            "appointment",
            "0014_alter_appointment_client_alter_appointment_provider_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="extra_documents",
            field=models.ManyToManyField(
                blank=True, related_name="extra_appointments", to="documents.document"
            ),
        ),
    ]
