# Generated by Django 4.2.5 on 2024-10-29 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documenttemplate_servicedocumentrequirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="service",
        ),
    ]
