# Generated by Django 4.2.5 on 2024-10-29 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_remove_document_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedocumentrequirement",
            name="document_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.documenttemplate",
            ),
        ),
    ]
