# Generated by Django 4.2.5 on 2024-10-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_servicedocumentrequirement_document_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="document",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_templates",
                to="documents.document",
            ),
            preserve_default=False,
        ),
    ]
