# Generated by Django 4.2.5 on 2024-11-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documenttemplate_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_templates",
                to="documents.document",
            ),
        ),
    ]
