# Generated by Django 4.2.5 on 2024-11-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_documenttemplate_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="file_content",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="file_types",
            field=models.CharField(
                default="pdf,jpg,jpeg",
                help_text="Comma-separated list of allowed file extensions",
                max_length=255,
            ),
        ),
    ]
