# Generated by Django 4.2.5 on 2024-11-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_file_document_file_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
