# Generated by Django 4.2.5 on 2024-12-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_service_id"),
        ("documents", "0008_document_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_templates",
                to="documents.document",
            ),
        ),
        migrations.AlterField(
            model_name="servicedocumentrequirement",
            name="document_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documenttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="servicedocumentrequirement",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_requirements",
                to="service.service",
            ),
        ),
    ]
